/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ElectionManagementSystem;
// for images
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author lifew
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        scaleImage();
        startProgress();
    }

    public void scaleImage() {
        ImageIcon icon = new ImageIcon(getClass().getResource("\\logo.png"));
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(logosplashscreen.getWidth(), logosplashscreen.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        logosplashscreen.setIcon(scaledIcon);
    }
    
    private void startProgress() {
        // Run the progress bar update in a separate thread
        new Thread(new Runnable() {
            public void run() {
                try {
                    for (int i = 0; i <= 100; i++) {
                        Thread.sleep(30);
                        final int progress = i;

                        // Update progress bar on the EDT
                        javax.swing.SwingUtilities.invokeLater(new Runnable() {
                            public void run() {
                                progressbar.setValue(progress);
                                progressbar.setStringPainted(true);

                                if(progress == 0) {
                                    statusprogress.setText("Setting things up...");
                                } else if(progress == 30) {
                                    statusprogress.setText("Almost there...");
                                } else if(progress == 50) {
                                    statusprogress.setText("Just a few more seconds...");
                                } else if(progress == 90) {
                                    statusprogress.setText("All done!");
                                }
                            }
                        });
                    }
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                // After progress is complete, show the next screen
                javax.swing.SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        // Close splash screen and open WelcomePage
                        new WelcomePage().setVisible(true);
                        SplashScreen.this.dispose();
                    }
                });
            }
        }).start();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logosplashscreen = new javax.swing.JLabel();
        progressbar = new javax.swing.JProgressBar();
        statusprogress = new javax.swing.JLabel();
        EMSLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Elections Management System - Splash Screen");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jPanel1.add(logosplashscreen);
        logosplashscreen.setBounds(310, 90, 200, 210);

        progressbar.setBackground(new java.awt.Color(204, 204, 204));
        progressbar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        progressbar.setForeground(new java.awt.Color(0, 199, 0));
        progressbar.setValue(50);
        progressbar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.white, java.awt.Color.green, java.awt.Color.white)));
        progressbar.setStringPainted(true);
        jPanel1.add(progressbar);
        progressbar.setBounds(90, 350, 630, 30);

        statusprogress.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        statusprogress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusprogress.setText("Setting things up...");
        jPanel1.add(statusprogress);
        statusprogress.setBounds(200, 330, 410, 14);

        EMSLabel1.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        EMSLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EMSLabel1.setText("Election Management System");
        jPanel1.add(EMSLabel1);
        EMSLabel1.setBounds(100, 50, 610, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(812, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        SplashScreen screen = new SplashScreen();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                screen.setVisible(true);
            }
        });
        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(40);
                screen.progressbar.setValue(i);
                screen.progressbar.setStringPainted(true);
                if(i==0)
                    screen.statusprogress.setText("Setting things up...");
                if(i==30)
                    screen.statusprogress.setText("Almost there...");
                if(i==50)
                    screen.statusprogress.setText("Just a few more seconds...");
                if(i==90)
                    screen.statusprogress.setText("All done!");
                    }
        } catch (Exception e) {
            
        }
        //user class screen
        WelcomePage n = new WelcomePage();
        //close or hide before open user class
        screen.setVisible(false);
        n.setVisible(true); //show user class screen
        
        //close splash screen 
        screen.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EMSLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logosplashscreen;
    private javax.swing.JProgressBar progressbar;
    private javax.swing.JLabel statusprogress;
    // End of variables declaration//GEN-END:variables
}
