/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ElectionManagementSystem;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author Laptop Point
 */
public class VoterVerify extends javax.swing.JInternalFrame {

    int selectedIndex;
    JDesktopPane v2;
    JButton back, login;
    JTabbedPane pan;
    /**
     * Creates new form VoterVerify
     */
    public VoterVerify(int index,  JDesktopPane v1, JButton Btn1, JButton Btn2, JTabbedPane pann) {
        initComponents();
        verify(index);
        ImageSize();
        v2=v1;
        back = Btn1;
        login = Btn2;
        pan=pann;
    }
    
    private void ImageSize() {
        ImageIcon icon = new ImageIcon(getClass().getResource("\\VoterVerify.jpg"));
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(verifyvoter.getWidth(), verifyvoter.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        verifyvoter.setIcon(scaledIcon);
        
        imgscale = img.getScaledInstance(verifyvoter1.getWidth(), verifyvoter1.getHeight(), Image.SCALE_SMOOTH);
        scaledIcon = new ImageIcon(imgscale);
        verifyvoter1.setIcon(scaledIcon);
    }
    
    
    public void verify(int index) {
        ArrayList<Voter> verifyvoter = main.voters;
        VoterNameVerify.setText(verifyvoter.get(index).getName().toUpperCase());
        VoterPAVerify.setText(verifyvoter.get(index).getProvincialAssemblyConstituency());
        VoterNAVerify.setText(verifyvoter.get(index).getNationalAssemblyConstituency());
        if(verifyvoter.get(index).getHasVoted() == false) {
            VoterVotingStatus.setText("NOT VOTED");
        } else {
            VoterVotingStatus.setText("VOTED");
        }
        
        selectedIndex = index;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        VoteButton = new javax.swing.JButton();
        VoteButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        VotingStatus = new javax.swing.JLabel();
        VoterNameVerify = new javax.swing.JLabel();
        VoterNAVerify = new javax.swing.JLabel();
        VoterPAVerify = new javax.swing.JLabel();
        VoterWelcome = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        VoterVotingStatus = new javax.swing.JLabel();
        verifyvoter = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        verifyvoter1 = new javax.swing.JLabel();

        setForeground(java.awt.Color.white);
        setTitle("Elections Management System - Voter's Verification");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        VoteButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        VoteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cancel.png"))); // NOI18N
        VoteButton.setText("CANCEL");
        VoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(VoteButton);
        VoteButton.setBounds(110, 220, 140, 30);

        VoteButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        VoteButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Verify.png"))); // NOI18N
        VoteButton1.setText("VERIFY");
        VoteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoteButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(VoteButton1);
        VoteButton1.setBounds(310, 220, 140, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Name:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 80, 160, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Provincial Assembly:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 110, 160, 20);

        VotingStatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        VotingStatus.setText("Voting Status:");
        jPanel1.add(VotingStatus);
        VotingStatus.setBounds(120, 170, 160, 20);

        VoterNameVerify.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        VoterNameVerify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VoterNameVerify.setText("XYZ");
        jPanel1.add(VoterNameVerify);
        VoterNameVerify.setBounds(290, 80, 160, 20);

        VoterNAVerify.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        VoterNAVerify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VoterNAVerify.setText("NA - ");
        jPanel1.add(VoterNAVerify);
        VoterNAVerify.setBounds(290, 140, 160, 20);

        VoterPAVerify.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        VoterPAVerify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VoterPAVerify.setText("PA - ");
        jPanel1.add(VoterPAVerify);
        VoterPAVerify.setBounds(290, 110, 160, 20);

        VoterWelcome.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        VoterWelcome.setForeground(new java.awt.Color(255, 255, 255));
        VoterWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VoterWelcome.setText("VOTER DETAILS:");
        jPanel1.add(VoterWelcome);
        VoterWelcome.setBounds(180, 10, 210, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("National Assembly:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 140, 160, 20);

        VoterVotingStatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        VoterVotingStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VoterVotingStatus.setText("NOT VOTED");
        jPanel1.add(VoterVotingStatus);
        VoterVotingStatus.setBounds(290, 170, 160, 20);

        verifyvoter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ElectionManagementSystem/VoterVerify.jpg"))); // NOI18N
        jPanel1.add(verifyvoter);
        verifyvoter.setBounds(0, 0, 730, 50);

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 70, 380, 130);

        verifyvoter1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ElectionManagementSystem/VoterVerify.jpg"))); // NOI18N
        jPanel1.add(verifyvoter1);
        verifyvoter1.setBounds(0, 270, 570, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 320);

        setBounds(110, 20, 593, 352);
    }// </editor-fold>//GEN-END:initComponents

    private void VoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoteButtonActionPerformed
        // TODO add your handling code here:
        // new VoterLogin().setVisible(true);
        //setTitle("Elections Management System - Voter Login");
        //MainPanel.setSelectedIndex(2);
        //VoterVerification.this.dispose();
        v2.setVisible(false);
        back.setVisible(true);
        login.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_VoteButtonActionPerformed

    private void VoteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoteButton1ActionPerformed
        this.dispose();
        pan.setSelectedIndex(3);     

    }//GEN-LAST:event_VoteButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VoteButton;
    private javax.swing.JButton VoteButton1;
    private javax.swing.JLabel VoterNAVerify;
    private javax.swing.JLabel VoterNameVerify;
    private javax.swing.JLabel VoterPAVerify;
    private javax.swing.JLabel VoterVotingStatus;
    private javax.swing.JLabel VoterWelcome;
    private javax.swing.JLabel VotingStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel verifyvoter;
    private javax.swing.JLabel verifyvoter1;
    // End of variables declaration//GEN-END:variables
}
